trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'jonwterraformsp-ARM'
    azureContainerRegistry: '{"loginServer":"jonwazdevopsacr.azurecr.io", "id" : "/subscriptions/2de0c33c-f475-4b47-932c-4788d7d5b84e/resourceGroups/RG-AzureDevOps2/providers/Microsoft.ContainerRegistry/registries/jonwazdevopsacr"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'

- task: CopyFiles@2
  inputs:
    Contents: 'deployment.yml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

