apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-cicdaksdotnetcore
  labels:
    app: cicdaksdotnetcore
spec:
  replicas: 1
  template:
    metadata:
      name: cicdaksdotnetcore
      labels:
        app: cicdaksdotnetcore
    spec:
      containers:
      - name: cicdaksdotnetcore
        image: nginx:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: cicdaksdotnetcore

---

apiVersion: v1
kind: Service
metadata:
  name: svc-cicdaksdotnetcore
spec:
  selector:
    app: cicdaksdotnetcore
  ports:
    - port: 80
  type: LoadBalancer
